# Generated by Django 3.2.6 on 2021-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-start']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[(1, 'RESERVED'), (0, 'CANCELLED')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
