# Generated by Django 3.2.6 on 2021-08-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210815_1052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('number', 'alias')},
        ),
    ]
