# Generated by Django 3.2.6 on 2021-08-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('number',), ('alias',)},
        ),
    ]
