# Generated by Django 3.2.6 on 2021-08-15 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='employees',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
