# Generated by Django 3.2.6 on 2021-08-15 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0007_auto_20210815_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organiser', to='auth.user', verbose_name='Organiser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='employees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Select current employees'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_people',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
